version: "2.3"

services:
  mls-analysis-service:
    build: .
    command: pserve development.ini --reload
    image: mls_analysis_service
    ports:
      - "6543:6543"
    volumes:
      - ./app:/app
      - /app/mls_analysis_service.egg-info
    environment:
      - CELERY_BROKER=amqp://admin:mypass@rabbitmq//
      - CELERY_BACKEND=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - default
      - external-nw

  celery:
    build: .
    command: celery -A celery_worker worker --concurrency=1 --max-tasks-per-child=100 --loglevel=INFO
    image: mls_analysis_service
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         capabilities: [gpu, utility, compute]
    volumes:
      - ./app:/app
      - /app/mls_analysis_service.egg-info
    environment:
      - CELERY_BROKER=amqp://admin:mypass@rabbitmq//
      - CELERY_BACKEND=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - mls-analysis-service
      - mongo
      - rabbitmq
    networks:
      - default
      - external-nw
  
  queue-dashboard:
    build: .
    image: mls_analysis_service
    command: celery -A celery_worker flower --port=5555 --broker=amqp://admin:mypass@rabbitmq//
    ports:
      - 5555:5555
    volumes:
      - ./app:/app
      - /app/mls_analysis_service.egg-info
    environment:
      - CELERY_BROKER=amqp://admin:mypass@rabbitmq//
      - CELERY_BACKEND=mongodb://root:example@mongo:27017/?authSource=admin
    depends_on:
      - rabbitmq
      - mongo
      - celery
    networks:
      - default
  
  rabbitmq:
    image: rabbitmq:latest
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=mypass
    networks:
      - default

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - default

networks:
  default:
  external-nw:
    external:
      name: sw-auto-mlss-network
